fn main() {
    generate_web_assets();
}

fn generate_web_assets() {
    use std::fmt::Write as _;
    use std::path::{Path, PathBuf};

    let output =
        PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set")).join("web_assets.rs");
    let profile = std::env::var("PROFILE").expect("PROFILE is set");
    let web_asset_dist = if profile == "release" {
        println!("cargo:rerun-if-env-changed=TROUVE_APP_UI_DIST");
        std::env::var_os("TROUVE_APP_UI_DIST")
    } else {
        // Debug preview hosts select a runtime directory or loopback Vite
        // server themselves. Do not watch or embed that directory: doing so
        // turns every frontend edit into an unnecessary Rust rebuild and can
        // leave a long-running Wry process on stale bytes.
        None
    };
    let mut source = String::from("// Generated by crates/trouve-app/build.rs.\n");
    writeln!(
        source,
        "const WEB_ASSETS_BUNDLED: bool = {};",
        web_asset_dist.is_some()
    )
    .expect("writing generated source");
    source.push_str(
        "fn bundled_web_assets() -> Result<\n\
             trouve_desktop_host::AssetManifest,\n\
             trouve_desktop_host::HostValidationError,\n\
         > {\n\
             use std::sync::Arc;\n\
             use trouve_desktop_host::{Asset, AssetManifest};\n\
             AssetManifest::new([\n",
    );

    let mut files = Vec::new();
    if let Some(dist) = web_asset_dist {
        let dist = PathBuf::from(dist)
            .canonicalize()
            .expect("TROUVE_APP_UI_DIST must name an existing desktop Vite output");
        // Vite content-hashes asset names. Watching the complete output tree is
        // required so a rebuilt bundle regenerates include_bytes! paths even
        // when TROUVE_APP_UI_DIST itself is unchanged.
        println!("cargo:rerun-if-changed={}", dist.display());
        collect_files(&dist, &mut files);
        files.sort();
        assert!(
            files.iter().any(|file| file == &dist.join("index.html")),
            "TROUVE_APP_UI_DIST must contain index.html"
        );
        assert!(
            !files.iter().any(|file| {
                file == &dist.join("service-worker.js") || file == &dist.join("pwa-meta.json")
            }),
            "TROUVE_APP_UI_DIST must be the desktop build, never the PWA artifact"
        );
        for file in &files {
            let relative = file
                .strip_prefix(&dist)
                .expect("collected asset stays under dist");
            let relative = relative
                .components()
                .map(|component| component.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/");
            let request_path = format!("/{relative}");
            if request_path.starts_with("/assets/") {
                assert!(
                    has_vite_content_hash(file),
                    "desktop asset names must carry Vite's eight-character content hash: {relative}"
                );
            }
            let file_path = file.to_string_lossy();
            assert!(
                !file_path.contains("\"#"),
                "asset path cannot terminate a raw string"
            );
            let content_type = content_type(file);
            let immutable = request_path.starts_with("/assets/") && request_path != "/index.html";
            writeln!(
                source,
                "        ({request_path:?}.to_string(), Asset {{ content_type: {content_type:?}.to_string(), bytes: Arc::from(&include_bytes!(r#\"{file_path}\"#)[..]), immutable: {immutable} }}),"
            )
            .expect("writing generated source");
        }
    } else {
        let desktop_preview_enabled = std::env::var_os("CARGO_FEATURE_WEB_PREVIEW").is_some()
            || std::env::var_os("CARGO_FEATURE_SERVO_PREVIEW").is_some();
        if desktop_preview_enabled {
            println!(
                "cargo:warning=no frontend assets were embedded; qualification targets may load TROUVE_APP_UI_DIST at runtime or proxy TROUVE_APP_UI_DEV_URL, while the product target will refuse to start"
            );
        }
        source.push_str(
            "        (\"/index.html\".to_string(), Asset {\n\
             content_type: \"text/html; charset=utf-8\".to_string(),\n\
             bytes: Arc::from(&br#\"<!doctype html><meta charset=utf-8><title>Trouve web preview</title><style>body{font:14px system-ui;padding:2rem;background:#17191e;color:#e4e6eb}code{background:#24272e;padding:.2rem}</style><h1>Web preview assets are unavailable</h1><p>Set <code>TROUVE_APP_UI_DIST</code> when launching this preview, or run the desktop Vite server and set <code>TROUVE_APP_UI_DEV_URL</code>.</p>\"#[..]),\n\
             immutable: false,\n\
             }),\n",
        );
    }
    source.push_str("    ])\n}\n");
    std::fs::write(output, source).expect("writing generated web asset manifest");

    fn collect_files(directory: &Path, output: &mut Vec<PathBuf>) {
        let mut entries = std::fs::read_dir(directory)
            .unwrap_or_else(|error| panic!("reading {}: {error}", directory.display()))
            .collect::<Result<Vec<_>, _>>()
            .unwrap_or_else(|error| panic!("reading {}: {error}", directory.display()));
        entries.sort_by_key(std::fs::DirEntry::file_name);
        for entry in entries {
            let path = entry.path();
            let kind = entry
                .file_type()
                .unwrap_or_else(|error| panic!("reading {}: {error}", path.display()));
            assert!(!kind.is_symlink(), "web assets may not contain symlinks");
            if kind.is_dir() {
                collect_files(&path, output);
            } else if kind.is_file() {
                output.push(path);
            }
        }
    }

    fn content_type(path: &Path) -> &'static str {
        match path.extension().and_then(std::ffi::OsStr::to_str) {
            Some("html") => "text/html; charset=utf-8",
            Some("js" | "mjs") => "text/javascript; charset=utf-8",
            Some("css") => "text/css; charset=utf-8",
            Some("json" | "webmanifest") => "application/json; charset=utf-8",
            Some("map") => "application/json; charset=utf-8",
            Some("wasm") => "application/wasm",
            Some("svg") => "image/svg+xml",
            Some("png") => "image/png",
            Some("ico") => "image/x-icon",
            Some("woff") => "font/woff",
            Some("woff2") => "font/woff2",
            Some("txt") => "text/plain; charset=utf-8",
            _ => "application/octet-stream",
        }
    }

    fn has_vite_content_hash(path: &Path) -> bool {
        let Some(stem) = path.file_stem().and_then(std::ffi::OsStr::to_str) else {
            return false;
        };
        let bytes = stem.as_bytes();
        bytes.len() >= 9
            && bytes[bytes.len() - 9] == b'-'
            && bytes[bytes.len() - 8..]
                .iter()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
    }
}
