#!/usr/bin/env python3
"""Generate the Lit frontend's semantic CSS palettes from the Slint source.

The migration keeps `crates/trouve-app/src/theme.rs` authoritative while both
frontends ship. This deliberately small parser understands the `Pal` constants
and struct-update inheritance used by that file; it fails closed when the
shape changes so a theme change cannot silently drift between frontends.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "crates/trouve-app/src/theme.rs"
OUTPUT = ROOT / "web/app-ui/src/styles/themes.generated.css"


class ThemeGenerationError(RuntimeError):
    """The Rust theme source no longer matches the supported declarative form."""


@dataclass(frozen=True)
class Theme:
    id: str
    dark: bool
    palette: dict[str, int]


def _palette_blocks(source: str) -> dict[str, tuple[dict[str, int], str | None]]:
    blocks: dict[str, tuple[dict[str, int], str | None]] = {}
    pattern = re.compile(
        r"(?:pub\s+)?const\s+(?P<name>[A-Z][A-Z0-9_]*)\s*:\s*Pal\s*=\s*Pal\s*\{"
        r"(?P<body>.*?)\n\};",
        re.DOTALL,
    )
    field_pattern = re.compile(r"^\s*([a-z][a-z0-9_]*)\s*:\s*0x([0-9a-fA-F]{8})\s*,", re.MULTILINE)
    base_pattern = re.compile(r"^\s*\.\.([A-Z][A-Z0-9_]*)\s*$", re.MULTILINE)

    for match in pattern.finditer(source):
        name = match.group("name")
        body = match.group("body")
        fields = {field: int(value, 16) for field, value in field_pattern.findall(body)}
        bases = base_pattern.findall(body)
        if len(bases) > 1:
            raise ThemeGenerationError(f"palette {name} has multiple bases")
        blocks[name] = (fields, bases[0] if bases else None)

    if not blocks:
        raise ThemeGenerationError("no Pal constants found")
    return blocks


def _resolve_palettes(
    blocks: dict[str, tuple[dict[str, int], str | None]],
) -> dict[str, dict[str, int]]:
    resolved: dict[str, dict[str, int]] = {}
    visiting: set[str] = set()

    def resolve(name: str) -> dict[str, int]:
        if name in resolved:
            return resolved[name]
        if name in visiting:
            raise ThemeGenerationError(f"palette inheritance cycle at {name}")
        try:
            fields, base = blocks[name]
        except KeyError as error:
            raise ThemeGenerationError(f"unknown palette {name}") from error
        visiting.add(name)
        palette = dict(resolve(base)) if base else {}
        palette.update(fields)
        visiting.remove(name)
        resolved[name] = palette
        return palette

    for name in blocks:
        resolve(name)
    return resolved


def parse_themes(source: str) -> list[Theme]:
    palettes = _resolve_palettes(_palette_blocks(source))
    table_match = re.search(
        r"pub\s+const\s+THEMES\s*:\s*&\[ThemeDef\]\s*=\s*&\[(?P<body>.*?)\n\];",
        source,
        re.DOTALL,
    )
    if table_match is None:
        raise ThemeGenerationError("THEMES table not found")
    entry_pattern = re.compile(
        r"ThemeDef\s*\{\s*id:\s*\"(?P<id>[^\"]+)\"\s*,"
        r".*?dark:\s*(?P<dark>true|false)\s*,"
        r".*?pal:\s*(?P<pal>[A-Z][A-Z0-9_]*)\s*,\s*\}",
        re.DOTALL,
    )
    themes: list[Theme] = []
    for match in entry_pattern.finditer(table_match.group("body")):
        palette_name = match.group("pal")
        try:
            palette = palettes[palette_name]
        except KeyError as error:
            raise ThemeGenerationError(
                f"theme {match.group('id')} uses unknown palette {palette_name}"
            ) from error
        themes.append(
            Theme(
                id=match.group("id"),
                dark=match.group("dark") == "true",
                palette=palette,
            )
        )
    if not themes:
        raise ThemeGenerationError("THEMES contains no entries")

    roles = set(themes[0].palette)
    if not roles:
        raise ThemeGenerationError("default theme has no semantic roles")
    for theme in themes[1:]:
        if set(theme.palette) != roles:
            missing = sorted(roles - set(theme.palette))
            extra = sorted(set(theme.palette) - roles)
            raise ThemeGenerationError(
                f"theme {theme.id} role mismatch: missing={missing}, extra={extra}"
            )
    return themes


def css_color(argb: int) -> str:
    alpha = (argb >> 24) & 0xFF
    red = (argb >> 16) & 0xFF
    green = (argb >> 8) & 0xFF
    blue = argb & 0xFF
    if alpha == 0xFF:
        return f"#{red:02x}{green:02x}{blue:02x}"
    return f"#{red:02x}{green:02x}{blue:02x}{alpha:02x}"


def render_css(themes: list[Theme]) -> str:
    lines = [
        "/* Generated by scripts/generate_web_themes.py; do not edit. */",
        "/* crates/trouve-app/src/theme.rs remains authoritative during migration. */",
        "",
    ]
    for index, theme in enumerate(themes):
        selector = f':root,\n[data-theme="{theme.id}"]' if index == 0 else f'[data-theme="{theme.id}"]'
        lines.append(f"{selector} {{")
        lines.append(f"  color-scheme: {'dark' if theme.dark else 'light'};")
        for role, value in theme.palette.items():
            lines.append(f"  --trouve-{role.replace('_', '-')}: {css_color(value)};")
        lines.extend(["}", ""])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)

    try:
        generated = render_css(parse_themes(args.source.read_text(encoding="utf-8")))
    except (OSError, ThemeGenerationError) as error:
        print(f"theme generation failed: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError as error:
            print(f"cannot read generated theme file: {error}", file=sys.stderr)
            return 1
        if current != generated:
            print(
                f"{args.output} is stale; run scripts/generate_web_themes.py",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    try:
        display_path = args.output.relative_to(ROOT)
    except ValueError:
        display_path = args.output
    print(f"wrote {display_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
